// use ferris_says::say;
// use std::io::{stdout, BufWriter};
// mod print;
// mod vars;
// mod types;
// mod strings;
// mod tuples;
// mod arrays;
// mod vectors;
// mod conditionals;
// mod functions;
// mod pointers;
// mod structs;
// mod enums;
mod cli;
fn main() {
    // print::print();
    // vars::run();
    // types::run();
    // strings::run();
    // tuples::run();
    // arrays::run();
    // vectors::run();
    // conditionals::run();
    // functions::run();
    // pointers::run();
    // structs::run();
    // enums::run();
    cli::run();
}
